spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: Order-Placed
    consumer:
      group-id: consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:com.example.Consumer.DTO.OrderDTO
        spring.json.trusted.packages: '*'

  mail:
    host: smtp.gmail.com
    port: 587
    username: 20cs156.shreyas@sjec.ac.in
    password: cckj ylhw lusl cxnq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8072