spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: Order-Placed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:com.example.Producer.DTO.OrderDTO


server:
  port: 8070

